### ISSUE TITLE
armor not showing on the hotbar

### ISSUE THREAD

**Issue by staarmaan** [Permdog99/Legacy-Reborn#2]
![Minecraft_ 1 20 4 27_06_2024 10_32_31 p  m](https://github.com/Permdog99/Legacy-Reborn/assets/109689489/cbf9d663-05a9-4a54-a235-63404d999e30)
![Minecraft_ 1 20 4 27_06_2024 10_32_21 p  m](https://github.com/Permdog99/Legacy-Reborn/assets/109689489/21283c45-e54e-4ab8-9410-44356273bc49)

**Comment by staarmaan** [comment]
also the buttons are inaccurate

**Comment by Permdog99** [comment]
This is a bug with NT and Legacy4J. Please set the HUD size to 1 for now.

**Comment by Permdog99** [comment]
I just tested and this has been fixed in 1.2.0
